### ISSUE TITLE
Is case sensitivity a bug or a feature?

### ISSUE THREAD

**Issue by Clarko** [capttaco/Briefs#4] opened 2009-12-04 21:37 UTC
Mismatched case on scene names and goto() actions will cause problems (SIGABRT)

Is case sensitivity something you're likely to use on purpose to differentiate "My Scene" from "My scene"? Or is it a trip hazard? I tend toward the latter.

This could either be a fix for briefs or a new feature for bs, which could be used to lowercase everything.

**Comment by josevazquez** [comment] 2009-12-08 08:10
Clarko, I just commited a new version of bs that should be case insensitive for scenes. Could you please verify that it works properly for you. I'm just a little concerned because when tried to reproduce the error, I in fact got an error, but not a (SIGABRT). So could you please double check. 

Also note that technically this was an issue for Briefs-Util, not Briefs. I don't have privileges for Briefs issues, so I can't close this issue. Capttaco: please close.

**Comment by Clarko** [comment] 2009-12-08 09:07
I've just double-checked the old behavior, then ran the same tests with the latest release of Briefs-util. New BS solves the case sensitivity problem! Thank you :)

And it just occurred to me why I was getting SIGABRT when you were getting errors. The SIGABRT I reported wasn't coming from BS (which I'm guessing is what you're worried is happening), it was coming from Briefs.app at runtime.

I'm not running BS by hand; I've got it running as part of an XCode script build phase. Script build phase errors aren't showing up as XCode build errors, so the building and installation go on uninterrupted.

Not an ideal situation, but running BS as a build phase saves me a little manual labor.

**Comment by josevazquez** [comment] 2009-12-09 07:44
Ahh, SIGABRT on briefs itself makes perfect sense. I need to try to make bs really bail out when it hits an error. As it works right now it, it prints errors to STDERR, but still dumps the output file to STDOUT. 

BTW I was actually meaning to start an Xcode template, but since you started that already, mind sharing that? 

I'm curious how errors are reported, if at all. I have been looking a little into making a template project and maybe a template target as well for BS. might be a little more involved than I'm bargaining for :-) 

Dude, thanks for your work checking this stuff out. I must admit, i've been lazy and haven't actually used the stuff much. I need to eat my dog food a bit more :-)

**Comment by capttaco** [comment] 2009-12-09 18:06
Clarko, you're boss. Thanks for checking this stuff out. I'll check out Briefs.app to make sure I'm checking for errors and not assuming too much when reading in the briefs.

And yea, share your Xcode scripts with the rest of us. Curious to see how it works. (or better yet, how about writing a blog post somewhere and sending us a link?) I'll post a link from @briefsapp to let everyone else know how awesome you are.

**Closed as completed by capttaco** 2009-12-09 18:06 UTC

**Comment by Clarko** [comment] 2009-12-10 07:18
Awww, flattery works every time. But I don't see how I deserve credit for finding bugs when you're the poor souls who go on to fix them! You guys are working on something that makes my life better, I owe you a debt of gratitude.

Regarding the build scripts: they're a bit brittle, so give me some time to embetter them and I'll share ;)
